# -*- coding: utf-8 -*-
"""embedding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XZVHSYMW7L0uUDaQ9VguCkGFejE9W-_r
"""

import utils as utils

from gensim.models import Word2Vec

import nltk
nltk.download('punkt')

# If running on colab, you'll need to mount your drive to access data files

from google.colab import drive
drive.mount('/content/drive')

sample_xml_presentations_path = utils.read_folder("sample_data/presentations/", "/content/sample_data/presentations")
sample_xml_papers_path = utils.read_folder("sample_data/papers/", "/content/sample_data/papers")

sample_xml_pres = utils.read_file(sample_xml_presentations_path[0])
sample_xml_pres

sample_xml_paper = utils.read_file(sample_xml_papers_path[0])
sample_xml_paper

# sample_xml_pres_path = "sample_data/presentations/slide.clean_tika.xml"
# sample_xml_pres = utils.read_file(sample_xml_pres_path)
# sample_xml_pres

# sample_xml_paper_path = "sample_data/papers/Paper_BRM.tei.xml"
# sample_xml_paper = utils.read_file(sample_xml_paper_path)
# sample_xml_paper

EMBEDDING_PRES_MODEL_FILE = "pres_word_model.txt"
EMBEDDING_PAPER_MODEL_FILE = "paper_word_model.txt"

sample_pres_text = utils.parse_xml(sample_xml_pres)
sample_pres_text

sample_paper_text = utils.parse_xml(sample_xml_paper)
print(sample_paper_text)

sample_pres_preprocessed = utils.preprocess_text(sample_pres_text)
sample_paper_preoricessed = utils.preprocess_text(sample_paper_text)

utils.preprocess_text(sample_paper_text)[0]

sample_paper_preprocessed = utils.preprocess_text(sample_paper_text)

print(sample_pres_preprocessed)

print(sample_paper_preprocessed)

presentation_word_model = Word2Vec(sentences = sample_pres_preprocessed, vector_size = 50, window = 5, min_count = 1, workers = 3, sg = 1)
paper_word_model = Word2Vec(sentences = sample_paper_preprocessed, vector_size = 50, window = 5, min_count = 1, workers = 3, sg = 1)

#Save the word embedding model to a file
presentation_word_model.wv.save_word2vec_format(EMBEDDING_PRES_MODEL_FILE, binary=False)
paper_word_model.wv.save_word2vec_format(EMBEDDING_PAPER_MODEL_FILE, binary=False)



